### ISSUE TITLE
License

### ISSUE THREAD

**Issue by halo** [xkvyor/bitmessage#1]
So does this work? :) Did you write the code from scratch?

Because I'm wondering which license you publish this code under. [MIT](http://opensource.org/licenses/MIT)?

PS: I noticed that your Ruby code does not follow any [convention](https://github.com/bbatsov/ruby-style-guide). Are you new to Ruby?

**Comment by xkvyor** [comment]
Hi, 

I think it just works for several test cases. I have not updated it for months.
Yes, I write this from scratch.
I am not very familiar with license and don't know which license I should use. But I think WTFPL is cool.
Yes, I am new to Ruby.

Thanks for reading my poor code. You are the first guy talk to me on github. :)
